export const FOLIAR_SCORE_FIELDS = [
  "nitrogenoTotal",
  "fosforo",
  "potasio",
  "calcio",
  "magnesio",
  "hierro",
  "manganeso",
  "zinc",
  "cobre",
  "boro",
  "sodio",
  "cloro",
  "clorofila",
];

export const FOLIAR_COLUMNS = [
  { field: "variedad", header: "Variedad" },
  { field: "nitrogenoTotal", header: "Nitrógeno total (%)" },
  { field: "fosforo", header: "Fósforo (%)" },
  { field: "potasio", header: "Potasio (%)" },
  { field: "calcio", header: "Calcio (%)" },
  { field: "magnesio", header: "Magnesio (%)" },
  { field: "hierro", header: "Hierro (ppm)" },
  { field: "manganeso", header: "Manganeso (ppm)" },
  { field: "zinc", header: "Zinc (ppm)" },
  { field: "cobre", header: "Cobre (ppm)" },
  { field: "boro", header: "Boro (ppm)" },
  { field: "sodio", header: "Sodio (ppm)" },
  { field: "cloro", header: "Cloro (%)" },
  { field: "clorofila", header: "Clorofila (Spad)" },
];

export const mapFoliarRow = (row) => ({
  year: Number(row["Temp."]),
  temp: row["Temp."],
  cuartel: row.Cuartel,
  variedad: row.Variedad,
  nitrogenoTotal: row["Nitrógeno total"],
  fosforo: row.fosforo,
  potasio: row.potasio,
  calcio: row.calcio,
  magnesio: row.magnesio,
  hierro: row.hierro,
  manganeso: row.manganeso,
  zinc: row.ziinc,
  cobre: row.cobre,
  boro: row.boro,
  sodio: row.sodio,
  cloro: row.cloro,
  clorofila: row.clorofila,
});
