import { BUD_ANALYSIS_EVENT, BUD_ANALYSIS_EVENT_ID } from "./budAnalysis/event";
import { FOLIAR_ANALYSIS_EVENT, FOLIAR_ANALYSIS_EVENT_ID } from "./foliarAnalysis/event";
import { PRE_PRUNING_COUNT_EVENT, PRE_PRUNING_COUNT_EVENT_ID } from "./prePruningCount/event";

export { BUD_ANALYSIS_EVENT_ID, FOLIAR_ANALYSIS_EVENT_ID, PRE_PRUNING_COUNT_EVENT_ID };

export const TIMELINE_EVENT_DEFINITIONS = [
  FOLIAR_ANALYSIS_EVENT,
  BUD_ANALYSIS_EVENT,
  PRE_PRUNING_COUNT_EVENT,
];

export const DATA_RECORDS_EVENT_IDS = [
  FOLIAR_ANALYSIS_EVENT_ID,
  BUD_ANALYSIS_EVENT_ID,
  PRE_PRUNING_COUNT_EVENT_ID,
];
